const mongoose=require("mongoose");
const cateringSchema=new mongoose.Schema({
    Name:{
        type:String,
        required:true
    },
    ServiceAddedBy:{
        type: mongoose.Schema.Types.ObjectId,
      ref: "service providers",
      required:true
    },
    TypeOfPreparation:{
        type:String,
        required:true
    },
    TypeOfSpread:{
        type:String,
        required:true
    },
    SpreadBifurcation:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    SoftDrinks:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    CrockeryPreferences:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    NonVegSnack:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    Deserts:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    VegDish:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    NonVegDish:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    VegSnack:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    Water:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
    FreshCannedJuice:{
        value:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        }
    },
   
},{timestamps:true})
const catering = new mongoose.model("catering",cateringSchema)
module.exports={catering}